### ISSUE TITLE
Estimated AWS Cost

### ISSUE THREAD

**Issue by jyoung2480** [openedx-unsupported/configuration#102]
The description of the edX configuration mentions that "this template will build quite a number of AWS resources that cost money, so please consider this before you start."

I realize that you pay for what you use with AWS, but seeing as I haven't used it yet, can anyone provide me an estimate of AWS costs when using edX?

Thanks!

**Comment by e0d** [comment]
If you use the AWS cloud formation wizard from the AWS web console, it will give you an estimated price at the last step.  We have tried to build in the ability to select the instance size and quantity for each component to give you control over pricing.  You can play around with the settings yourself.  Note that in many cases we have set the reference capacity defaults to two because this is a reference deployment template and any deployment should have redundancy for key services.  

Look for the link "Estimated cost" in the "Stack Information" section on the Review step.

**Comment by jyoung2480** [comment]
Excellent, thanks!

**Comment by raunakp** [comment]
How is the billing done? Is it based on the stack creation or the number of hours the stack is up? Can I shut down and turn ON the stack as and when required?
