### ISSUE TITLE
No .boto config file in jenkins_admin

### ISSUE THREAD

**Issue by rodo** [openedx-unsupported/configuration#1139]
Hi,

There is no configuration for EWS credentials used by **abbey.py** in the **jenkins_admin** playbook. I propose to add a template files to add boto config file in jenkins's users home in jenkins_admin playbook. The templates will use vars for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

This is the way I run abbey.py, but if you use another solution that you think is better I'll open to discuss and contribute your solution.

**Comment by feanil** [comment]
Hi Randolph we currently setup our Jenkins instance with an IAM role that gives it the correct permissions.  Boto is able to detect the IAM role and use it without any further configuration.  Though in the future we may need what you are suggesting because we will need the admin Jenkins to work with multiple accounts.  If you have a PR that adds a boto file to the admin instance I think it should support the ability to have multiple sets of credentials.

**Comment by rodo** [comment]
@feanil thanks for your comment I understand better now. I'll look to add multiple credentials to the boto, and look forward about IAM, I'll love to see edX deployment works on OpenStack too, so I'll look how to support credentials without IAM. I have no PR open yet, I'll post here when it'll be ready if nobody is against this idea.

**Comment by feanil** [comment]
Sounds good.  Since the PR will also notify us I'm gonna close this issue for now.
