### ISSUE TITLE
SSH Issue & BAD Gateway Issue

### ISSUE THREAD

**Issue by catftp** [openedx-unsupported/configuration#1144]
After completing installation and restarting edx server, i am unable to get logged in through SSh and having following error

Disconnect: No supported authentication methods available (server sent: publikey) and when i try to open in web browser having bad gateway error. 

Please Help

**Comment by jarv** [comment]
Please include more information like how the server was installed, what instructions you followed, and what your starting point was. By default we disable ssh password authentication so you will need to use key authentication to login.

**Comment by catftp** [comment]
I deployed open edx through instruction given in https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation, and started from scratch. initially its working fine and okay. but suddenly i was unable to ssh that server. lms page is opening but with 18010 port, its not opening.

**Comment by hkim823** [comment]
The instructions do say that SSH configs are by default configured to disable password based logins.  I suspect that's exactly what happened here.  Please either change the defaults in https://github.com/edx/configuration/blob/master/playbooks/roles/common/defaults/main.yml so that COMMON_SSH_PASSWORD_AUTH is yes

I'm going to put in a PR to address this right in the edx_sandbox.yml file

**Comment by catftp** [comment]
hkim: can you guide me how can i able to access through ssh either with keys or password.
