### ISSUE TITLE
How to build edx in Microsoft Azure?

### ISSUE THREAD

**Issue by tvvocold** [openedx-unsupported/configuration#1231]
i creat a ubuntu12.04 env and followed One step installation and finally i got 
TASK: [common | pip install virtualenv] **************************************\* 
changed: [localhost] => (item=pip==1.5.4)
changed: [localhost] => (item=virtualenv==1.11.4)
then nothing...why and how to fix?
i have try to add 80 port in azure

**Comment by devota** [comment]
I got it to work  by doing the manual installation and edit the main.yml in /var/tmp/configuration/playbooks/roles/edxapp/defaults 
The fields I edited was the ones referring to the site name and URL as well as "normal login" to "yes" so that I could access the server after restart. When the script: cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"  was finished I had to restart again, and then it worked fine. You also need to open port 18010 to be able to use the "Studio".
