### ISSUE TITLE
edX Ubuntu 12.04 64 bit Installation uses vulnerable to attack version elasticsearch

### ISSUE THREAD

**Issue by cheluskin** [openedx-unsupported/configuration#1826]
I received a message from a hosting provider that the server has been compromised through a vulnerable version of elasticsearch.

**Comment by feanil** [comment]
@cheluskin When was the server last updated, when the Elasticsearch vulnerability was first discovered we added [this](https://github.com/edx/configuration/blob/master/playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/elasticsearch.yml.j2#L19-L22) to resolve it since we are unable to upgrade the version of elasticsearch right now.  If you have not run the elasticsearch role recently, that change may not have been applied to your elasticsearch configuration.
