### ISSUE TITLE
Question - without virtenv for python and ruby

### ISSUE THREAD

**Issue by geneliu** [openedx-unsupported/configuration#276]
Hi everyone,

Is there a plan to configure/deploy edx without virtenv of python and ruby? In a real production environment, I would like to use system python/ruby environment. I am very interested in this project. Just need some suggestions to start with.

Thanks,
Gene

**Comment by feanil** [comment]
Hi @geneliu We currently use virtual environments in our productions system, it allows a lot more control over the versions of packages we use than using the system packages.  It also allows us to upgrade much faster than most OS package systems tend to.  There are no plans currently to move to system packages instead of using virtual environments.
