### ISSUE TITLE
Xenial blocker: install bower dependencies

### ISSUE THREAD

**Issue by nedbat** [openedx-unsupported/configuration#3492]
Installing with CONFIGURATION_VERSION=ned/xenial-native (commit 207a6e9), it fails at:
```
TASK: [insights | install bower dependencies] *********************************
failed: [localhost] => {"changed": true, "cmd": ". /edx/app/insights/venvs/insights/bin/activate && . /edx/app/insights/nodeenvs/insights/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/bower install --production --config.interactive=false", "delta": "0:00:00.259206", "end": "2016-11-23 03:35:13.014525", "rc": 1, "start": "2016-11-23 03:35:12.755319", "warnings": []}
stderr: module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/edx/app/insights/edx_analytics_dashboard/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

FATAL: all hosts have already failed -- aborting
```
@edx/devops ideas?

**Comment by nedbat** [comment]
@edx/analytics is this familiar?

**Comment by jonoda** [comment]
Just for additional context, it is also impacting the native installs using the automated sandbox and the [analytics standalone stack](https://openedx.atlassian.net/wiki/display/OpenOPS/edX+Analytics+Installation), both calling the insights playbook. 

@mulby mentioned that bower does have transient issues from time to time, but is unsure if what we're seeing is the same problem.

With some collaborative digging in #analytics on slack, [PR 582](https://github.com/edx/edx-analytics-dashboard/commit/686e96bfc8e6921d8620e6316a2580dc408397d3) in the edx-analytics-dashboard could be a possibility. Maybe @thallada can help comment? It roughly corresponds to the timing of when the most recent successful sandbox installation occurred and when I started to see the same problem.

**Comment by dsjen** [comment]
I'm seeing this too now on an AMI I tried to build.  I'm going to create a bug, dig in a bit more, and will be in touch.

**Comment by dsjen** [comment]
FYI, I upgraded my version of node locally and am able to reproduce this error.

**Comment by dsjen** [comment]
It looks like this error is caused by some special combination of node and bower.  I was able to reproduce this using bower 1.7.2 (which Insights is pinned to) upon upgrading to a newer patch release (1.7.9) the error went away.

It looks like there was a change in a downstream package to bower that was resolved in a later version.  Fun times with dependency management!  https://github.com/nodejs/node/issues/1898 was a helpful thread.

I will put up a PR for Insights very soon.

**Comment by bmanfranssen** [comment]
Hi @dsjen and @nedbat, during a clean installation on Ubuntu Server 12.04 on some of our stacks I now also receive the same error as mentioned above. I saw that there is a reference to #584, but do you know whether there is any estimation on when this error is going to be fixed by any chance? (_I am relatively new to the Github process of fixing issues. Also, I am retrying fresh installations but it keeps on persisting so it's better to stop now and wait for it to be fixed I guess_). Thanks for all the help!

**Comment by theroadnotaken** [comment]
I am trying to install using https://openedx.atlassian.net/wiki/display/OpenOPS/edX+Analytics+Installation and encountered the issue in Installing Bower dependencies. 

I was able to install successfully on Friday 18th Nov though.

**Comment by jibsheet** [comment]
@nedbat  The OPS ticket is OPS-1907

**Comment by nedbat** [comment]
It looks like this was fixed with this PR: https://github.com/edx/edx-analytics-dashboard/pull/584
