### ISSUE TITLE
Error when executing make docker.pkg

### ISSUE THREAD

**Issue by dalareo** [openedx-unsupported/configuration#3543]
#Steps to replicate:
- executing make docker.pkg

Syntax error at docker.mk file:

````
.build/%/Dockerfile.pkg: docker/build/%/Dockerfile Makefile
	@mkdir -p .build/$*
@sed -E "s#FROM edxops/([^:]+)(:\S*)?#FROM \1:test#" $< > $@
````

the last line should be:

````
@sed -E "s#FROM edxops/([^:]+)(:\S*)?#FROM \1:latest#" $< > $@

**Comment by nedbat** [comment]
@clintonb What do you think of this?  It does look like Dockerfile.test and Dockerfile.pkg have identical actions in docker.mk

**Comment by dalareo** [comment]
But no edxops/precise-common:test image is available!!, e.g

**Comment by clintonb** [comment]
I must defer to @cpennington since he wrote the file originally. I only modified it to get things building on OS X (https://github.com/edx/configuration/pull/2868/commits/7cd04db1d90b57c67a098c83ae322697492415e0), but I (clearly) did not attempt to use all of the Make targets.

@dalareo what goal can we help you achieve? Do you need these targets to work? If we decide to get rid of them (since it seems no one has used them) would you mind?

@cpennington what was your original intent with these targets?

**Comment by dalareo** [comment]
I am trying to deploy Edx with Docker and I need to build and package images first, ad lobg as there is no available versions for all the services at Docker Hub
