### ISSUE TITLE
Problem while stack creating (no outputs)

### ISSUE THREAD

**Issue by gitim** [openedx-unsupported/configuration#421]
I am trying to build stack vs cloudformation. Following this guide https://github.com/edx/configuration/wiki/AWS-Installation i launched creation of the new stack, but after several minute of creation it returned CREATE_FAILED status and there wasn't not any output in outputs tab. What's the problem? Can anyone help to solve it?

**Comment by feanil** [comment]
The reason for the failure can usually be found underneath the events tab.
There is a reason column and if you scroll down to the first failure it
should tell you why it failed.   There are probably other failures as well
that happen because cloudformation tries to stop the build when anything
fails.  There are a few prameters that need to be updated before building
the stack, and that is usually the reason the build fails.

**Comment by gitim** [comment]
Thanks a lot,  feanil! Yes, there were several errors, and i solved them vs your answers for some earlier issues, but i still have errors. In MongoServerASGroup was raised: Only one subnet per availability-zone is supported in each AutoScalingGroup. I tried to change in edx-reference-architecture.json in DesiredCapacity parts default number to 1 and Minsize, Maxsize to 1, but it didn't work. Can u offer some solution for this? Excuse me for maybe stupid questions, i am creating cloudformation for the first time.

**Comment by gitim** [comment]
new commits solved problem
