### ISSUE TITLE
lms.env.json is lost during update

### ISSUE THREAD

**Issue by janadel** [openedx-unsupported/configuration#661]
Hi,
I use the following command to update my production installation 
ansible-playbook edxapp.yml -c local -i 'localhost',  --tags deploy 

The problem is that i loose lms.env.json file every time i am updating ?

How can I prevent this from happening ?

Thanks.

**Comment by feanil** [comment]
Hi what do you mean by lose?  Is it being deleted or just moved?  A few releases back we moved everything to a new directory structure under a top level '/edx' folder by default.  Are you using the new structure or the old structure or something else?  Also can you post a gist of the output of that command when you run it?

**Comment by jarv** [comment]
@janadel we have a fix for this in master, the reason for the issue is because update is re-running ansible with the defaults.  If you had any custom variables defined (like EDXAPP_SITENAME, etc) they will go back to what they are set to in the `<role>/defaults/main.yml`.  To work around this the edx_ansible role now drops a var file in /edx/etc that has all of the variable definitions that the update scripts picks up on subsequent runs.  
In the meantime the easiest workaround is to edit the `/edx/app/edx_ansible/edx_ansible/playbooks/roles/edxapp/defaults/main.yml` file with your settings and re-run the update script.

**Comment by janadel** [comment]
Hi,
1.I use the new directory structure.
2.I mean that my lms.env.json is overwritten by the default one and so i am losing the changes  I have done
3.The update command (ansible-playbook edxapp.yml -c local -i 'localhost', --tags deploy ) finishes without any errors.

Thanks for you help.

**Comment by jbau** [comment]
Do you update lms.env.json on the machine itself?  Then ansible will overwrite it, and this is the correct behavior.  If you want to change the variables you should be either reading in a set of other var_files, or setting them in your playbook.

**Comment by jarv** [comment]
@jbau see my earlier reply
